version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
  web:
    build:
      context: ./web
      args:
        SYNC_API_URL: 'http://localhost:3000'
    ports:
      - 8080:8080
  sync:
    build: ./sync
    ports:
      - 3000:3000
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DATABASE_NAME=todo
      - REDIS_URL=redis:6379
